import Head from 'next/head';

const HeadSeo = ({ title, single }) => {
  return (
    <Head>
      <title>{single ? `${title} | ${single}` : title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
export default HeadSeo;
